name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- Frontend ---------- #
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: ESLint (frontend)
        working-directory: frontend
        run: npm run lint -- --max-warnings=0

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # ---------- Backend ---------- #
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install backend dependencies
        working-directory: backend
        run: pipenv install --dev --deploy --ignore-pipfile

      - name: Backend tests
        working-directory: backend
        env:
          # Minimal env vars so imports succeed; values are dummy for tests
          OPENAI_API_KEY: "test-key"
        run: pipenv run pytest -q 